[build]
  command = "yarn build"
  publish = "client/build"

[[redirects]]
  from = "/*"
  to = "/server.js"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
